// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDnEVoG1XQAL92zEj5ohQskVBP1Po7QUuM',
    appId: '1:349068557799:web:7ac34ef1e445318aaf5142',
    messagingSenderId: '349068557799',
    projectId: 'klinigim-cepte',
    authDomain: 'klinigim-cepte.firebaseapp.com',
    storageBucket: 'klinigim-cepte.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDtbv2Mk7CCiZRjRXbx-h0iwmz1DjBa5-s',
    appId: '1:349068557799:android:8e43ee0553d94e33af5142',
    messagingSenderId: '349068557799',
    projectId: 'klinigim-cepte',
    storageBucket: 'klinigim-cepte.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD0b9uEEnztGM5S_FJksH7AH3-ofn2tDWM',
    appId: '1:349068557799:ios:5ae28a3aa34ede79af5142',
    messagingSenderId: '349068557799',
    projectId: 'klinigim-cepte',
    storageBucket: 'klinigim-cepte.firebasestorage.app',
    iosBundleId: 'com.example.hastaTakip',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD0b9uEEnztGM5S_FJksH7AH3-ofn2tDWM',
    appId: '1:349068557799:ios:5ae28a3aa34ede79af5142',
    messagingSenderId: '349068557799',
    projectId: 'klinigim-cepte',
    storageBucket: 'klinigim-cepte.firebasestorage.app',
    iosBundleId: 'com.example.hastaTakip',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDnEVoG1XQAL92zEj5ohQskVBP1Po7QUuM',
    appId: '1:349068557799:web:b8767dc873ca2bc4af5142',
    messagingSenderId: '349068557799',
    projectId: 'klinigim-cepte',
    authDomain: 'klinigim-cepte.firebaseapp.com',
    storageBucket: 'klinigim-cepte.firebasestorage.app',
  );
}
